language: node_js
node_js:
  - "6.14.13"
branches:
  only:
    - main
cache:
  directories:
    - node_modules

install:
  - npm install

notifications:
  email: false

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  keep_history: true
  on:
    branch: main
  fqdn: esogelola.com
