language: node_js
node_js:
  - "14"
branches:
  only:
    - main
cache:
  directories:
    - node_modules

install:
  - npm install
  - npm install -g yarn

notifications:
  email: false

script:
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  keep_history: true
  on:
    branch: main
  fqdn: esogelola.com
